#!/bin/bash

# Setup Monthly YouTube Video Quality Checks
# This script helps set up automated monthly checks

echo "📅 Setting up Monthly YouTube Video Quality Checks"
echo ""

# Check if cron is available
if ! command -v crontab &> /dev/null; then
    echo "⚠️  crontab not found. Manual setup required."
    echo ""
    echo "To set up monthly checks manually:"
    echo "1. Open crontab: crontab -e"
    echo "2. Add this line (runs on 1st of each month at 9 AM):"
    echo "   0 9 1 * * cd /path/to/slctrips-v2 && node check-youtube-fidelity.mjs >> logs/youtube-check.log 2>&1"
    echo ""
    exit 1
fi

# Get project directory
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SCRIPT_PATH="$PROJECT_DIR/check-youtube-fidelity.mjs"
LOG_DIR="$PROJECT_DIR/logs"

# Create logs directory
mkdir -p "$LOG_DIR"

# Create monthly check script
MONTHLY_SCRIPT="$PROJECT_DIR/scripts/monthly-youtube-check.sh"
cat > "$MONTHLY_SCRIPT" << 'EOF'
#!/bin/bash
# Monthly YouTube Video Fidelity Check
# Auto-generated by setup-monthly-checks.sh

cd "$(dirname "$0")/.."
LOG_FILE="logs/youtube-check-$(date +%Y-%m).log"

echo "==========================================" >> "$LOG_FILE"
echo "Monthly YouTube Check - $(date)" >> "$LOG_FILE"
echo "==========================================" >> "$LOG_FILE"
echo "" >> "$LOG_FILE"

node check-youtube-fidelity.mjs >> "$LOG_FILE" 2>&1

# Check results and send alert if issues found
RELEVANCE_RATE=$(node -e "
  const fs = require('fs');
  try {
    const report = JSON.parse(fs.readFileSync('youtube-fidelity-report.json', 'utf8'));
    const rate = (report.relevant / report.checked * 100).toFixed(1);
    console.log(rate);
  } catch(e) {
    console.log('0');
  }
" 2>/dev/null)

ERROR_RATE=$(node -e "
  const fs = require('fs');
  try {
    const report = JSON.parse(fs.readFileSync('youtube-fidelity-report.json', 'utf8'));
    const rate = (report.errors / report.checked * 100).toFixed(1);
    console.log(rate);
  } catch(e) {
    console.log('0');
  }
" 2>/dev/null)

if (( $(echo "$RELEVANCE_RATE < 80" | bc -l 2>/dev/null || echo "0") )); then
  echo "⚠️  WARNING: Relevance rate below 80%: ${RELEVANCE_RATE}%" >> "$LOG_FILE"
fi

if (( $(echo "$ERROR_RATE > 10" | bc -l 2>/dev/null || echo "0") )); then
  echo "⚠️  WARNING: Error rate above 10%: ${ERROR_RATE}%" >> "$LOG_FILE"
fi

echo "" >> "$LOG_FILE"
echo "Check complete. Review $LOG_FILE for details." >> "$LOG_FILE"
EOF

chmod +x "$MONTHLY_SCRIPT"

# Check if cron job already exists
CRON_CMD="0 9 1 * * cd $PROJECT_DIR && $MONTHLY_SCRIPT"
if crontab -l 2>/dev/null | grep -q "monthly-youtube-check"; then
    echo "✅ Monthly check already configured in crontab"
else
    echo "📝 Adding monthly check to crontab..."
    (crontab -l 2>/dev/null; echo "$CRON_CMD") | crontab -
    echo "✅ Monthly check added to crontab"
    echo "   Schedule: 1st of each month at 9:00 AM"
fi

echo ""
echo "✅ Setup complete!"
echo ""
echo "Monthly checks will run on the 1st of each month at 9:00 AM"
echo "Logs will be saved to: $LOG_DIR/youtube-check-YYYY-MM.log"
echo ""
echo "To view current cron jobs: crontab -l"
echo "To remove: crontab -e (then delete the line)"
echo ""

