-- Seed states table (optional; run after 008_states.sql).
-- SDPC membership as of 2026. ecosystem_available = true only for UT (has full ecosystem in code).
INSERT INTO states (code, name, sdpc_member, ecosystem_available, last_updated) VALUES
  ('AL', 'Alabama', true, false, NULL),
  ('AK', 'Alaska', false, false, NULL),
  ('AZ', 'Arizona', true, false, NULL),
  ('AR', 'Arkansas', true, false, NULL),
  ('CA', 'California', true, false, NULL),
  ('CO', 'Colorado', true, false, NULL),
  ('CT', 'Connecticut', true, false, NULL),
  ('DE', 'Delaware', true, false, NULL),
  ('DC', 'District of Columbia', true, false, NULL),
  ('FL', 'Florida', true, false, NULL),
  ('GA', 'Georgia', true, false, NULL),
  ('HI', 'Hawaii', true, false, NULL),
  ('ID', 'Idaho', true, false, NULL),
  ('IL', 'Illinois', true, false, NULL),
  ('IN', 'Indiana', true, false, NULL),
  ('IA', 'Iowa', true, false, NULL),
  ('KS', 'Kansas', true, false, NULL),
  ('KY', 'Kentucky', true, false, NULL),
  ('LA', 'Louisiana', true, false, NULL),
  ('ME', 'Maine', true, false, NULL),
  ('MD', 'Maryland', true, false, NULL),
  ('MA', 'Massachusetts', true, false, NULL),
  ('MI', 'Michigan', true, false, NULL),
  ('MN', 'Minnesota', true, false, NULL),
  ('MS', 'Mississippi', true, false, NULL),
  ('MO', 'Missouri', true, false, NULL),
  ('MT', 'Montana', true, false, NULL),
  ('NE', 'Nebraska', true, false, NULL),
  ('NV', 'Nevada', true, false, NULL),
  ('NH', 'New Hampshire', true, false, NULL),
  ('NJ', 'New Jersey', true, false, NULL),
  ('NM', 'New Mexico', true, false, NULL),
  ('NY', 'New York', true, false, NULL),
  ('NC', 'North Carolina', true, false, NULL),
  ('ND', 'North Dakota', true, false, NULL),
  ('OH', 'Ohio', true, false, NULL),
  ('OK', 'Oklahoma', true, false, NULL),
  ('OR', 'Oregon', true, false, NULL),
  ('PA', 'Pennsylvania', true, false, NULL),
  ('RI', 'Rhode Island', true, false, NULL),
  ('SC', 'South Carolina', true, false, NULL),
  ('SD', 'South Dakota', true, false, NULL),
  ('TN', 'Tennessee', true, false, NULL),
  ('TX', 'Texas', true, false, NULL),
  ('UT', 'Utah', true, true, '2026-01'),
  ('VT', 'Vermont', true, false, NULL),
  ('VA', 'Virginia', true, false, NULL),
  ('WA', 'Washington', true, false, NULL),
  ('WV', 'West Virginia', true, false, NULL),
  ('WI', 'Wisconsin', true, false, NULL),
  ('WY', 'Wyoming', true, false, NULL)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  sdpc_member = EXCLUDED.sdpc_member,
  ecosystem_available = EXCLUDED.ecosystem_available,
  last_updated = EXCLUDED.last_updated,
  updated_at = now();
