/**
 * State foundation profiles — CSV-derived baseline for all 50 states + DC.
 * Source: US State Student Data Privacy and AI Governance Profiles (Table 1).
 * SDPC membership from lib/ecosystem/types.ts (canonical list).
 */

import type { StateFoundation } from './foundation-types'
import { SDPC_MEMBER_STATES } from './types'

function sdpc(code: string): boolean {
  return SDPC_MEMBER_STATES.includes(code)
}

export const STATE_FOUNDATION: Record<string, StateFoundation> = {
  AL: {
    code: 'AL',
    name: 'Alabama',
    sdpcMember: sdpc('AL'),
    agencyName: 'Alabama State Department of Education (ALSDE)',
    stateLaws: [
      { name: 'Alabama Child Protection Act of 2024', code: 'HB 168; Ala. Code § 14A-6-240', description: 'AI governance committees; expands CSAM to include AI depictions.' },
    ],
    federalLawsNote: 'FERPA, PPRA, COPPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: 'Mandatory compliance audits; specific AI vendor contract language prohibiting unauthorized training.',
    dpaAvailable: null,
    aiGovernanceNotes: 'AI Policy Template (2024) based on NIST standards; mandates human-in-the-loop; safe harbor for manipulated political media with disclaimer.',
  },
  AK: {
    code: 'AK',
    name: 'Alaska',
    sdpcMember: false,
    agencyName: 'Alaska Dept. of Education & Early Development (DEED)',
    stateLaws: [],
    federalLawsNote: 'FERPA, COPPA, CIPA',
    contactEmail: 'eed.contact@alaska.gov',
    contactPhone: '(907) 465-2800',
    website: 'https://education.alaska.gov/',
    requiredRolesSummary: 'Data Privacy Officers (district level recommended); AI K12 Advisory Group.',
    complianceSummary: '6-Step Policy Development Process; annual policy reviews; vendor vetting protocols; focus on cultural responsiveness and remote connectivity.',
    dpaAvailable: true,
    aiGovernanceNotes: '2025 K-12 AI framework focusing on ethics and literacy; mandates AI tools affirm diverse cultures and warns against misappropriation.',
  },
  AZ: {
    code: 'AZ',
    name: 'Arizona',
    sdpcMember: sdpc('AZ'),
    agencyName: 'Arizona State Dept. of Education',
    stateLaws: [
      { name: 'Student Data Privacy', code: 'SB 1450 (ARS Title 15 § 15-142); HB 2088; SB 1314', description: 'Parental consent for assessments; opt-out for directory info; operator prohibitions on targeted advertising.' },
    ],
    federalLawsNote: 'FERPA, PPRA, COPPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: 'Parental consent for assessments; opt-out for directory info; operator prohibitions on targeted advertising.',
    dpaAvailable: null,
    aiGovernanceNotes: null,
  },
  AR: {
    code: 'AR',
    name: 'Arkansas',
    sdpcMember: sdpc('AR'),
    agencyName: 'Division of Elementary and Secondary Education',
    stateLaws: [
      { name: 'Student Data Privacy', code: 'HB 1961 (AR Code § 6-18-109)', description: 'Public entities must create AI authorized use policies; prohibits operators from profiling or selling covered info.' },
    ],
    federalLawsNote: 'FERPA, PPRA, COPPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: 'Public entities must create AI authorized use policies (H 1958); prohibits operators from profiling or selling covered info.',
    dpaAvailable: null,
    aiGovernanceNotes: 'H 1876 clarifies ownership of AI-generated content; H 1283 (Failed) sought digital media standards in K-12.',
  },
  CA: {
    code: 'CA',
    name: 'California',
    sdpcMember: sdpc('CA'),
    agencyName: 'California Department of Education (CDE)',
    stateLaws: [
      { name: 'SOPIPA', code: 'Bus. & Prof. Code § 22584-22585', description: 'Student Online Personal Information Protection Act.' },
      { name: 'Third-Party Contracts', code: 'AB 1584 (CA Educ. Code § 49073.1)', description: 'Education records and third-party contracts.' },
      { name: 'Social Media Privacy', code: 'AB 1442 (CA Educ. Code § 49073.6)', description: 'Social media privacy.' },
      { name: 'Social Security Numbers', code: 'AB 2097 (CA Educ. Code § 49076.7)', description: 'Superintendent assigns student IDs.' },
      { name: 'CCPA/CPRA', code: 'Cal. Civ. Code § 1798.100', description: 'Consumer privacy.' },
      { name: 'CA AI Transparency Act', code: 'SB 942/AB 853 (Cal. Bus. & Prof. Code § 22757)', description: 'AI detection and disclosures.' },
    ],
    federalLawsNote: 'FERPA, PPRA, COPPA',
    contactEmail: null,
    contactPhone: null,
    website: 'https://www.cde.ca.gov/ds/dp/',
    requiredRolesSummary: 'CDE Chief Privacy Officer; Records Officer (Gov. Code § 12270); Superintendent assigns student IDs (AB 2097).',
    complianceSummary: 'Strict data minimization; mandatory deletion on request; vendors barred from non-educational data use; risk assessments for sensitive info; security procedures for covered info.',
    dpaAvailable: true,
    aiGovernanceNotes: 'Executive Order N-12-23; CDE GenAI guidance; AB 2013 (training data transparency); SB 942 requires AI detection/disclosures.',
  },
  CO: {
    code: 'CO',
    name: 'Colorado',
    sdpcMember: sdpc('CO'),
    agencyName: 'Colorado Department of Education',
    stateLaws: [
      { name: 'Student Data Transparency and Security Act', code: 'HB 14-1294, HB 16-1423', description: 'Data inventory and security management.' },
      { name: 'Security Breach and PII Disposal', code: 'HB 18-1128 (Colo. Rev. Stat. § 6-1-713)', description: 'Breach and PII disposal.' },
      { name: 'Colorado AI Act', code: 'SB 24-205 (Colo. Rev. Stat. § 6-1-1701, effective Feb 1, 2026)', description: 'Bans algorithmic discrimination.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: 'State Board of Education/Department of Education (data inventory & security per HB 14-1294); Colorado Attorney General (AI oversight per SB 24-205).',
    complianceSummary: 'SBE must publish data inventory; CPA mandates privacy risk assessments; mandatory breach notification within 30 days; HB 21-1110 web accessibility.',
    dpaAvailable: null,
    aiGovernanceNotes: 'SB 205 (effective 2026) bans algorithmic discrimination; 2024 Statewide Roadmap for AI in K-12; 2025 AI Skills Progression Guide.',
  },
  CT: {
    code: 'CT',
    name: 'Connecticut',
    sdpcMember: sdpc('CT'),
    agencyName: 'Connecticut Department of Education',
    stateLaws: [
      { name: 'Student Data Privacy', code: 'HB 5469 (CT Gen St § 10-234aa); HB 5444', description: 'Task force to study student data privacy.' },
      { name: 'CT Data Privacy Act', code: '§§ 42-515 et seq.', description: 'State data privacy.' },
      { name: 'Act Concerning AI', code: 'SB 1103', description: 'Controllers must disclose if data used to train LLMs; assessment for disparate impact.' },
    ],
    federalLawsNote: 'FERPA, PPRA, COPPA',
    contactEmail: null,
    contactPhone: null,
    website: 'https://portal.ct.gov/SDE',
    requiredRolesSummary: null,
    complianceSummary: 'Written contracts for data sharing; mandatory breach notification; prohibitions on targeted advertising/profiling; state agency AI inventory required.',
    dpaAvailable: true,
    aiGovernanceNotes: 'SB 1103 (Act Concerning AI); requires controllers to disclose if data is used to train LLMs; assessment of AI for disparate impact.',
  },
  DE: {
    code: 'DE',
    name: 'Delaware',
    sdpcMember: sdpc('DE'),
    agencyName: null,
    stateLaws: [
      { name: 'Student Data Privacy', code: 'SB 79 (DE Code Tit 14 § 8101A); SB 208', description: 'Student Data Privacy Task Force.' },
    ],
    federalLawsNote: 'FERPA, PPRA, COPPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: 'Providers must implement security and delete data; prohibited from selling data or targeted advertising.',
    dpaAvailable: null,
    aiGovernanceNotes: null,
  },
  DC: {
    code: 'DC',
    name: 'District of Columbia',
    sdpcMember: sdpc('DC'),
    agencyName: 'Local Education Agency (LEA)',
    stateLaws: [
      { name: 'Protecting Students Digital Privacy Act', code: 'B21-0578 (DC Code § 38-831.01)', description: 'Mandatory security in LEA contracts; prohibits social media password access.' },
    ],
    federalLawsNote: 'FERPA, PPRA, COPPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: 'Mandatory security in LEA contracts; prohibits social media password access.',
    dpaAvailable: null,
    aiGovernanceNotes: null,
  },
  FL: {
    code: 'FL',
    name: 'Florida',
    sdpcMember: sdpc('FL'),
    agencyName: 'Florida Department of Education',
    stateLaws: [
      { name: 'Student Data Privacy', code: 'SB 188 (FL St § 1002.22); HB 731; HB 662 (2023); FL St § 1012.34', description: 'District Superintendent evaluation authority.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: 'District Superintendent (evaluation authority).',
    complianceSummary: 'Prohibits collection of biometric/political info; mandatory use of VAM (50% of evaluation); prohibits bargaining on teacher evaluations; prohibits use of SSN as ID; prohibits operators from selling student info.',
    dpaAvailable: null,
    aiGovernanceNotes: null,
  },
  GA: {
    code: 'GA',
    name: 'Georgia',
    sdpcMember: sdpc('GA'),
    agencyName: 'Georgia Department of Education (GaDOE)',
    stateLaws: [
      { name: 'Student Data Privacy', code: 'SB 89 (GA Code § 20-2-660)', description: 'Prohibits AI for high-stakes tasks (IEP goals, grading); prohibits service providers from using data for commercial purposes.' },
    ],
    federalLawsNote: 'FERPA, PPRA, COPPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: 'Prohibits AI for high-stakes tasks; prohibits service providers from using data for commercial purposes.',
    dpaAvailable: null,
    aiGovernanceNotes: "Adopted 'Traffic Light' system (Red/Yellow/Green) for classroom AI; Ethical Considerations in the Appropriate Use of AI for Educators (2025).",
  },
  HI: {
    code: 'HI',
    name: 'Hawaii',
    sdpcMember: sdpc('HI'),
    agencyName: 'Hawaii Department of Education',
    stateLaws: [
      { name: 'Student Data Privacy', code: 'SB 2607 (HI Rev St § 302A-500)', description: 'Institutional Analyst; centralized review; transition to NDPA.' },
    ],
    federalLawsNote: 'FERPA, COPPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: 'Institutional Analyst.',
    complianceSummary: 'Centralized review process for software; unified helpdesk for tool requests; transition to National Data Privacy Agreement (NDPA).',
    dpaAvailable: true,
    aiGovernanceNotes: 'Curriculum leaders engaged with safe classroom AI use as part of the privacy review process.',
  },
  ID: {
    code: 'ID',
    name: 'Idaho',
    sdpcMember: sdpc('ID'),
    agencyName: 'State Board of Education',
    stateLaws: [
      { name: 'Student Data Accessibility Act', code: 'Idaho Code § 33-133 / SB 1372', description: 'Create student data system; public privacy policies; security and destruction plans; prohibit biometric collection.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: 'Create student data system; public privacy policies; develop security and destruction plans; prohibit biometric collection.',
    dpaAvailable: null,
    aiGovernanceNotes: null,
  },
  IL: {
    code: 'IL',
    name: 'Illinois',
    sdpcMember: sdpc('IL'),
    agencyName: 'Board of Higher Education / State Board of Education',
    stateLaws: [
      { name: 'SOPIPA', code: '105 ILCS 85/1 et seq. (Amended by SB 1796)', description: 'Student Online Personal Protection Act.' },
      { name: 'ISSRA', code: 'Illinois School Student Records Act', description: 'School student records.' },
      { name: 'Statewide AI Guidance Mandate', code: 'SB 1920', description: 'State Board of Education to develop statewide AI guidance.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: 'Task forces and agency oversight; no statutorily mandated individual roles like Student Data Manager as in Utah.',
    complianceSummary: 'Student Online Personal Protection Act (SOPPA); data sharing agreements required for PII.',
    dpaAvailable: null,
    aiGovernanceNotes: 'State guidance on AI in education.',
  },
  IN: {
    code: 'IN',
    name: 'Indiana',
    sdpcMember: sdpc('IN'),
    agencyName: 'Department of Education',
    stateLaws: [],
    federalLawsNote: 'FERPA (general consumer data protection via Ind. Code § 24-15-1)',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: null,
    dpaAvailable: null,
    aiGovernanceNotes: 'H 1296 (Failed) proposed guidelines, model AI policy, and inventory of AI platforms. No AI governance found.',
  },
  IA: {
    code: 'IA',
    name: 'Iowa',
    sdpcMember: sdpc('IA'),
    agencyName: null,
    stateLaws: [
      { name: 'Student Personal Information Protection Act', code: 'HF 2354 (Iowa Code § 279.71)', description: 'Prohibits operators from targeted advertising, profiling, or selling student information.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: 'Prohibits operators from targeted advertising, profiling, or selling student information.',
    dpaAvailable: null,
    aiGovernanceNotes: null,
  },
  KS: {
    code: 'KS',
    name: 'Kansas',
    sdpcMember: sdpc('KS'),
    agencyName: 'State Board of Regents',
    stateLaws: [
      { name: 'Student Data Privacy Act', code: 'SB 367 (KS St § 72-6312); HB 2008; HB 2209', description: 'SOPPA; prohibits targeted advertising and biometric collection; mandatory breach notification; annual reports to governor.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: 'SOPPA; prohibits targeted advertising and biometric collection; mandatory breach notification; annual reports to governor.',
    dpaAvailable: null,
    aiGovernanceNotes: null,
  },
  KY: {
    code: 'KY',
    name: 'Kentucky',
    sdpcMember: sdpc('KY'),
    agencyName: null,
    stateLaws: [
      { name: 'Cloud Computing / Student Privacy', code: 'Ky. Rev. Stat. Ann. §§ 367.3611 et seq.; HB 232 (KY Rev St § 365.734)', description: 'Mandatory breach notification; cloud services prohibited from commercial use of data; requires AI disclosure in public decision-making.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: 'Mandatory breach notification; cloud services prohibited from commercial use of data; requires AI disclosure in public decision-making.',
    dpaAvailable: null,
    aiGovernanceNotes: '2025 Senate bill passed to regulate state government\'s use of AI. KDE guidance: AI-directed, AI-supported, and AI-empowered learning paradigms.',
  },
  LA: {
    code: 'LA',
    name: 'Louisiana',
    sdpcMember: sdpc('LA'),
    agencyName: 'Louisiana Department of Education (LDOE)',
    stateLaws: [
      { name: 'Louisiana Student Privacy Law', code: 'R.S. 17:3914; HB 718; HB 1076; App Store Accountability Act', description: 'Local school superintendents direct audits (HB 1076).' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: 'Local school superintendents direct audits (HB 1076).',
    complianceSummary: 'Prohibits requesting social media logins; 10-day records request limit; $10,000 fine for violations; cyclical four-component policy approach.',
    dpaAvailable: null,
    aiGovernanceNotes: 'Four-tier AI integration system (AI-Empowered to Prohibited) aligned with SAMR model; requires app store age assurance.',
  },
  ME: {
    code: 'ME',
    name: 'Maine',
    sdpcMember: sdpc('ME'),
    agencyName: 'Maine Department of Education',
    stateLaws: [
      { name: 'Student Information Privacy Act', code: 'Me. Rev. Stat. tit. 20-A, § 951-953', description: 'SEA acts as state agent for SDPC; cybersecurity guidance aligned with NIST/ISO.' },
    ],
    federalLawsNote: 'FERPA, COPPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: 'Director of Education Data; Tech Infrastructure Specialist; Data Quality Trainer.',
    complianceSummary: 'SEA acts as state agent for SDPC; provides cybersecurity guidance aligned with NIST/ISO.',
    dpaAvailable: true,
    aiGovernanceNotes: 'LD 1727 (chatbots legislation); state team focuses on AI and digital equity collaboration through SDPC. DOE "Keep the Human in AI" toolkit; advises against AI detection tools.',
  },
  MD: {
    code: 'MD',
    name: 'Maryland',
    sdpcMember: sdpc('MD'),
    agencyName: 'Maryland State Department of Education (MSDE)',
    stateLaws: [
      { name: 'Student Data Privacy Act of 2015', code: 'HB 298 (Md. Code Ann., Educ. § 4-131)', description: 'Student data privacy.' },
      { name: 'Education - AI', code: 'HB 1297/SB 0979', description: 'AI Oversight Employee (local level); guidelines and annual AI inventories.' },
      { name: 'Data Privacy Best Practices', code: 'HB 568 (Md. Code Ann., Educ. § 7-2101)', description: 'Data privacy best practices.' },
    ],
    federalLawsNote: 'FERPA, PPRA, COPPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: 'AI Oversight Employee (HB 1297/SB 0979); Artificial Intelligence Subcabinet (Governor\'s Executive Council - HB 129); Maryland DIT collaborates with MSDE.',
    complianceSummary: 'Annual AI system inventories; impact assessments for AI systems; public availability of inventories; MLDS links data for 20 years.',
    dpaAvailable: null,
    aiGovernanceNotes: 'HB 1297/SB 0979 effective July 2024; mandates development of AI guidelines, standards, and best practices for county boards. Mandatory AI policies.',
  },
  MA: {
    code: 'MA',
    name: 'Massachusetts',
    sdpcMember: sdpc('MA'),
    agencyName: 'Massachusetts Dept. of Elementary and Secondary Education (DESE)',
    stateLaws: [
      { name: 'AI Policies in Schools', code: 'H 614 (pending 2025)', description: 'Voluntary state guidance framework; DESE guidelines for 2025-2026.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: 'https://www.doe.mass.edu/edtech/ai/default.html',
    requiredRolesSummary: 'District Operations Leadership; DESE AI Task Force; Office of Educational Technology (EdTech) within DESE.',
    complianceSummary: 'Districts urged to establish AI disclosure expectations; minimize use of AI detection tools.',
    dpaAvailable: null,
    aiGovernanceNotes: 'Massachusetts Guidance for AI in K-12 Education (2025-2026); emphasizes academic integrity and AI literacy; addresses "digital design divide"; advises against AI detection tools.',
  },
  MI: {
    code: 'MI',
    name: 'Michigan',
    sdpcMember: sdpc('MI'),
    agencyName: 'Michigan Department of Education (MDE)',
    stateLaws: [
      { name: 'SOPPA', code: 'SB 510 (Mich. Comp. Laws § 388.1291-1295)', description: 'Student Online Personal Protection Act.' },
      { name: 'Protection of Pupil Privacy', code: 'S 33 (Mich. Comp. Laws § 380.1136)', description: 'Pupil privacy.' },
    ],
    federalLawsNote: 'FERPA, COPPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: 'MDE vendor contracts/privacy oversight; Wayne RESA - AI guidance development.',
    complianceSummary: 'Evaluation systems must include growth data; performance is "majority factor" in RIF; seniority cannot be considered.',
    dpaAvailable: null,
    aiGovernanceNotes: 'Michigan Virtual\'s AI Integration Framework (3-stage maturity model) endorsed by MDE as official state guidance.',
  },
  MN: {
    code: 'MN',
    name: 'Minnesota',
    sdpcMember: sdpc('MN'),
    agencyName: null,
    stateLaws: [
      { name: 'Educational Data; Technology Providers', code: 'Minn. Stat. § 13.32 / HF 2353', description: 'Educational data and technology providers.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: null,
    dpaAvailable: null,
    aiGovernanceNotes: 'MDE guidance emphasizing equity and centering people in decision-making.',
  },
  MS: {
    code: 'MS',
    name: 'Mississippi',
    sdpcMember: sdpc('MS'),
    agencyName: 'Mississippi Department of Education',
    stateLaws: [
      { name: 'AI Regulation Task Force', code: 'SB 2426', description: 'Oversight; Mississippi lacks comprehensive SOPIPA-like student data privacy legislation.' },
    ],
    federalLawsNote: 'FERPA, COPPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: 'Director of IT Security and Data Privacy (Jason Hageman); Office of Technology and Strategic Services.',
    complianceSummary: 'Privacy/governance built into SIS design; use of simplified National Data Privacy Agreement (NDPA).',
    dpaAvailable: true,
    aiGovernanceNotes: 'MDE guidance organized around five components of digital learning.',
  },
  MO: {
    code: 'MO',
    name: 'Missouri',
    sdpcMember: sdpc('MO'),
    agencyName: null,
    stateLaws: [
      { name: 'Student Data Accessibility, Transparency, and Accountability Act', code: 'Mo. Rev. Stat. § 161.096 / HB 1490', description: 'Student data transparency and accountability.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: null,
    dpaAvailable: null,
    aiGovernanceNotes: 'DESE "AI Guidance for Local Education Agencies" Version 1.0 for 2025-26 school year.',
  },
  MT: {
    code: 'MT',
    name: 'Montana',
    sdpcMember: sdpc('MT'),
    agencyName: 'Montana Office of Public Instruction (OPI)',
    stateLaws: [
      { name: 'Montana Pupil Online Personal Information Protection Act', code: 'HB 745 (Mont. Code Ann. § 20-7-1325)', description: 'Pupil online personal information.' },
      { name: 'Montana Government AI Use Law', code: 'HB 178 (2024)', description: 'Disclosure for AI-generated material; human review for decisions with legal effects.' },
    ],
    federalLawsNote: 'FERPA, COPPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: 'Constitutional Players framework (OPI/LEAs).',
    complianceSummary: 'Mandatory compliance with state laws; biannual AI guideline review; government AI decisions must be human-reviewed (HB 178).',
    dpaAvailable: null,
    aiGovernanceNotes: 'Indigenous data sovereignty; AI tools must not alter/remix tribally authored materials; Right to Compute Act (SB 212). OPI and Montana Digital Academy guidance for biennial review.',
  },
  NE: {
    code: 'NE',
    name: 'Nebraska',
    sdpcMember: sdpc('NE'),
    agencyName: null,
    stateLaws: [
      { name: 'Student Online Personal Protection Act', code: 'Neb. Rev. Stat. § 79-2,153 / LB 512', description: 'Student online personal information protection.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: null,
    dpaAvailable: null,
    aiGovernanceNotes: 'Guidance released.',
  },
  NV: {
    code: 'NV',
    name: 'Nevada',
    sdpcMember: sdpc('NV'),
    agencyName: null,
    stateLaws: [
      { name: 'Student Data Privacy', code: 'SB 463 (NRS 386.650)', description: 'Information Security and Privacy Policy (2015); vendor disclosure, security plans, PII restrictions.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: 'cameron.carey@doe.nv.gov',
    contactPhone: null,
    website: 'https://doe.nv.gov/offices/office-of-information-technology/student-data-privacy',
    requiredRolesSummary: 'Cameron Carey, Director, Information Technology',
    complianceSummary: 'Prohibits targeted advertising and selling student data.',
    dpaAvailable: null,
    aiGovernanceNotes: 'Nevada AI Alliance (2025); STELLAR framework - prohibits AI surveillance, ensures AI complements educators.',
  },
  NH: {
    code: 'NH',
    name: 'New Hampshire',
    sdpcMember: sdpc('NH'),
    agencyName: 'NH Department of Education',
    stateLaws: [
      { name: 'Student and Teacher Information Protection and Privacy', code: 'HB 1612 (NH RSA 189:65-68)', description: 'Minimum Standards for Privacy and Security (2018); LEA privacy governance plans; vendor contract requirements.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: 'https://www.education.nh.gov/who-we-are/data-governance',
    requiredRolesSummary: null,
    complianceSummary: 'Prohibits transfer of sensitive data to for-profit entities without consent.',
    dpaAvailable: null,
    aiGovernanceNotes: 'NH Learning Initiative (NHLI) PreK-12 Gen AI Framework; State AI Task Force.',
  },
  NJ: {
    code: 'NJ',
    name: 'New Jersey',
    sdpcMember: sdpc('NJ'),
    agencyName: 'New Jersey Department of Education (NJDOE)',
    stateLaws: [
      { name: 'SOPPA-NJ', code: 'A4978', description: 'Prohibits ed-tech data sales/targeted ads; written contracts required.' },
      { name: 'NJDPA', code: 'S332', description: 'Data protection assessments mandatory.' },
    ],
    federalLawsNote: 'FERPA, COPPA',
    contactEmail: null,
    contactPhone: null,
    website: 'https://www.nj.gov/education/innovation/ai/',
    requiredRolesSummary: 'Office of Innovation - AI & EdTech; active AI governance ($1.5M FY2025, TeachAI, NJSDPC/A4L, NJETA).',
    complianceSummary: 'SOPPA-NJ: prohibits ed-tech data sales/targeted ads; written contracts required; NJDPA: data protection assessments mandatory.',
    dpaAvailable: true,
    aiGovernanceNotes: 'Comprehensive AI initiative: grant programs; "Teaching with AI" & "Teaching about AI" curriculum; TeachAI participation; Office of Innovation oversees.',
  },
  NM: {
    code: 'NM',
    name: 'New Mexico',
    sdpcMember: sdpc('NM'),
    agencyName: 'New Mexico Public Education Department (NMPED)',
    stateLaws: [],
    federalLawsNote: 'FERPA, COPPA (HM 54, HM 20 for AI study)',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: 'Exploring: AI Work Group (HM 2), NM Digital Equity in Education Act guidance (May 2025).',
    complianceSummary: 'Utilizes M.A.Z.E. framework (Monitor, Assess, Zero-in, Evaluate); requires disclosure of AI assistance in coursework.',
    dpaAvailable: null,
    aiGovernanceNotes: '5-level AI Assessment Scale for integrity; core protections based on White House AI Bill of Rights. Exploring AI governance.',
  },
  NY: {
    code: 'NY',
    name: 'New York',
    sdpcMember: sdpc('NY'),
    agencyName: 'New York State Education Department (NYSED)',
    stateLaws: [
      { name: 'Education Law Section 2-d', code: '8 NYCRR 121.8; SB 6356; AB A6787D; State Tech Law § 106-B', description: 'Data privacy and security; State Chief Privacy Officer; District Data Privacy Officer.' },
    ],
    federalLawsNote: 'FERPA, PPRA, COPPA',
    contactEmail: 'privacy@nysed.gov',
    contactPhone: null,
    website: 'http://www.nysed.gov/data-privacy-appendix',
    requiredRolesSummary: 'State Chief Privacy Officer; District Data Privacy Officer (8 NYCRR 121.8).',
    complianceSummary: 'Mandatory Data Privacy and Security Plans for vendors; Parents\' Bill of Rights; ban on biometric ID tech; data minimization restricted to strictly necessary elements.',
    dpaAvailable: true,
    aiGovernanceNotes: 'NYSED AI Guidance Framework (2024) - human-in-the-loop and bias audits; NYC Local Law 144 (automated employment); state agency AI inventory. LOADinG Act proposed.',
  },
  NC: {
    code: 'NC',
    name: 'North Carolina',
    sdpcMember: sdpc('NC'),
    agencyName: null,
    stateLaws: [],
    federalLawsNote: 'FERPA only (SB 2295 - higher ed research records; no K-12 specific privacy act)',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: null,
    dpaAvailable: null,
    aiGovernanceNotes: 'NCDPI "CRAFT" prompting framework guidebook.',
  },
  ND: {
    code: 'ND',
    name: 'North Dakota',
    sdpcMember: sdpc('ND'),
    agencyName: null,
    stateLaws: [],
    federalLawsNote: 'FERPA only',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: null,
    dpaAvailable: null,
    aiGovernanceNotes: 'State guidance including implementation roadmap and checklist.',
  },
  OH: {
    code: 'OH',
    name: 'Ohio',
    sdpcMember: sdpc('OH'),
    agencyName: 'Ohio Department of Education and Workforce (DEW)',
    stateLaws: [
      { name: 'Student Data Privacy / Technology Providers', code: 'O.R.C. § 3319.321; SB 29 (O.R.C. §§ 3319.325, 3319.326, 3319.327)', description: 'Annual notice for device monitoring; 72-hour notice for specific access; mandatory destruction of records within 90 days of contract end.' },
    ],
    federalLawsNote: 'FERPA, COPPA, CIPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: 'Annual notice for device monitoring; 72-hour notice for specific access; mandatory destruction of records within 90 days of contract end.',
    dpaAvailable: null,
    aiGovernanceNotes: 'SB 29 limits electronic monitoring; all public schools must adopt board-approved AI policies by mid-2026; state model policy due end of 2025. Mandatory AI policies.',
  },
  OK: {
    code: 'OK',
    name: 'Oklahoma',
    sdpcMember: sdpc('OK'),
    agencyName: null,
    stateLaws: [
      { name: 'Student Data Accessibility, Transparency, and Accountability Act', code: '70 O.S. § 3-168 / HB 1989', description: 'Student data transparency and accountability.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: null,
    dpaAvailable: null,
    aiGovernanceNotes: 'OSDE "AI Acceptable Use Rating Scale".',
  },
  OR: {
    code: 'OR',
    name: 'Oregon',
    sdpcMember: sdpc('OR'),
    agencyName: 'Oregon Department of Education (ODE)',
    stateLaws: [
      { name: 'Oregon Student Information Protection Act (OSIPA)', code: 'ORS 336.184; ORS 339.356', description: 'District Information Security Officer; Records Officer (ORS 192.311).' },
    ],
    federalLawsNote: 'FERPA, PPRA, COPPA, CIPA',
    contactEmail: 'ode.digitallearning@ode.oregon.gov',
    contactPhone: null,
    website: 'https://www.oregon.gov/ode/reports-and-data/Pages/Student-Data-Privacy.aspx',
    requiredRolesSummary: 'District Information Security Officer (ORS 336.184); Records Officer (ORS 192.311).',
    complianceSummary: 'Prohibits targeted advertising; vendor data disposal within 60 days of termination; annual retirement audit for EdTech products.',
    dpaAvailable: true,
    aiGovernanceNotes: 'Developing Policy and Protocols for GenAI in K-12; focuses on instructional integration, ethical risks, and mitigating bias.',
  },
  PA: {
    code: 'PA',
    name: 'Pennsylvania',
    sdpcMember: sdpc('PA'),
    agencyName: null,
    stateLaws: [],
    federalLawsNote: 'FERPA only (2025 legislation focuses on CSAM)',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: 'Interim Policy on Use of GenAI requires human review of outputs; personnel responsible for accuracy.',
    dpaAvailable: null,
    aiGovernanceNotes: 'Exploring - legislation pending for Keystone AI Authority; no K-12 specific framework found. Judicial/Bar AI policies exist.',
  },
  RI: {
    code: 'RI',
    name: 'Rhode Island',
    sdpcMember: sdpc('RI'),
    agencyName: null,
    stateLaws: [
      { name: 'Student Data Privacy (Cloud Computing)', code: 'R.I. Gen. Laws § 16-103-1 / HB 7124', description: 'Student data privacy in cloud computing.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: null,
    dpaAvailable: null,
    aiGovernanceNotes: 'RIDE comprehensive framework including procurement checklists and grade-level use cases.',
  },
  SC: {
    code: 'SC',
    name: 'South Carolina',
    sdpcMember: sdpc('SC'),
    agencyName: 'South Carolina Department of Education',
    stateLaws: [
      { name: 'Data Collection and Privacy', code: 'S.C. Code Ann. § 59-1-490 / HB 3893', description: 'Required district data governance plans; privacy impact assessments; data classification frameworks.' },
    ],
    federalLawsNote: 'FERPA, COPPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: 'Chief Privacy Officer; CISO.',
    complianceSummary: 'Required district data governance plans; privacy impact assessments; data classification frameworks.',
    dpaAvailable: true,
    aiGovernanceNotes: 'H 4754 (Real Estate AI); CPO advancing AI initiatives through IAPP insights.',
  },
  SD: {
    code: 'SD',
    name: 'South Dakota',
    sdpcMember: sdpc('SD'),
    agencyName: null,
    stateLaws: [
      { name: 'Student Privacy and Data Protection', code: 'S.D. Codified Laws § 13-3-51 / SB 63', description: 'Student privacy and data protection.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: null,
    dpaAvailable: null,
    aiGovernanceNotes: 'Legislation focused on political deepfakes. No K-12 AI governance found.',
  },
  TN: {
    code: 'TN',
    name: 'Tennessee',
    sdpcMember: sdpc('TN'),
    agencyName: 'Tennessee Department of Education',
    stateLaws: [
      { name: 'Student Data / AI Policies', code: 'Public Chapter 550 (2024); Tenn. Code Ann. §§ 47-18-3201 et seq.', description: 'Directors of Schools mandated annual reporting; all districts must adopt AI policies.' },
      { name: 'ELVIS Act', code: 'HB 2091', description: 'AI voice/likeness security.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: 'Directors of Schools (mandated annual reporting).',
    complianceSummary: 'All districts must adopt AI policies; annual reporting from Directors to Board by June; opt-out for automated decision-making.',
    dpaAvailable: null,
    aiGovernanceNotes: 'ELVIS Act protects against voice cloning; TSBA Model Policy 4.214; strict prohibition on entering PII or IP into AI systems. Mandatory AI policies.',
  },
  TX: {
    code: 'TX',
    name: 'Texas',
    sdpcMember: sdpc('TX'),
    agencyName: 'Texas Education Agency (TEA)',
    stateLaws: [
      { name: 'Student Data / Operator Restrictions', code: 'HB 2087 (Ed. Code § 32.151)', description: 'Restricts operator use.' },
      { name: 'Cybersecurity Coordinator', code: 'SB 820 (Ed. Code § 11.175)', description: 'Superintendent designates Cybersecurity Coordinator.' },
      { name: 'Texas Data Privacy and Security Act', code: 'Bus & Com Code § 541.051', description: 'State data privacy and security.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: 'Superintendent designates Cybersecurity Coordinator (SB 820).',
    complianceSummary: 'Cybersecurity framework mandatory; breach reporting to agency; data minimization standards; informed consent for mental health software.',
    dpaAvailable: null,
    aiGovernanceNotes: 'TRAIGA (HB 149); prohibits AI social scoring by gov; state agencies must inventory AI; age verification for AI sexual material tools. Exploring K-12 guidance.',
  },
  UT: {
    code: 'UT',
    name: 'Utah',
    sdpcMember: sdpc('UT'),
    agencyName: 'Utah State Board of Education (USBE)',
    stateLaws: [
      { name: 'Student Data Protection Act (SDPA)', code: 'U.C.A. §§ 53E-9-301 et seq.; Utah FERPA U.C.A. § 53E-9-2', description: 'Director of Privacy; LEA Student Data Manager; CISO; Records Officer.' },
      { name: 'Board Rule', code: 'R277-487', description: 'Public school data confidentiality and disclosure.' },
      { name: 'GRAMA', code: 'Title 63G, Ch. 2', description: 'Public records.' },
      { name: 'Utah AI and Policy Act', code: 'SB 149', description: 'Office of AI Policy.' },
    ],
    federalLawsNote: 'FERPA, PPRA, COPPA, IDEA, NSLA',
    contactEmail: 'privacy@schools.utah.gov',
    contactPhone: '(801) 538-7500',
    website: 'https://www.schools.utah.gov/studentdataprivacy',
    requiredRolesSummary: 'Director of Privacy (53E-9-302(4)); CISO (Policy 05.02); Records Officer (63G-2-103(24)); LEA Student Data Manager (53E-9-303); Privacy Advisory Group.',
    complianceSummary: 'Adopt Data Governance Plan; maintain Metadata Dictionary; annual info security awareness course; breach reporting within 10 days; annual Privacy Practices Benchmark; 45-day record access response.',
    dpaAvailable: true,
    aiGovernanceNotes: 'Utah AI and Policy Act (SB 149) established Office of AI Policy; USBE P-12 AI Framework (2024) prohibits PII in consumer AI and AI use for IEP goals or subjective grading.',
  },
  VT: {
    code: 'VT',
    name: 'Vermont',
    sdpcMember: sdpc('VT'),
    agencyName: null,
    stateLaws: [],
    federalLawsNote: 'FERPA only',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: null,
    dpaAvailable: null,
    aiGovernanceNotes: 'Legislation focuses on state government inventory; no K-12 framework found.',
  },
  VA: {
    code: 'VA',
    name: 'Virginia',
    sdpcMember: sdpc('VA'),
    agencyName: 'Virginia Department of Education (VDOE)',
    stateLaws: [
      { name: 'School Service Providers / Student Data', code: 'HB 1 (VA Code §§ 22.1-287); SB 951; HB 2350 (22.1-20.2)', description: 'Chief Data Security Officer (HB 2350).' },
      { name: 'Consumer Data Protection Act', code: '§§ 59.1-575 et seq.', description: 'Consumer data protection.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: 'Chief Data Security Officer (HB 2350).',
    complianceSummary: 'Incident reporting within 24 hours; mandatory model data security plan; restrictions on facial recognition; parent right to download record copies.',
    dpaAvailable: null,
    aiGovernanceNotes: 'HB 2031 prohibits police facial recognition until 2026; focus on transparency and prevention of algorithmic discrimination. VDOE guidelines on benefits, privacy, and equity.',
  },
  WA: {
    code: 'WA',
    name: 'Washington',
    sdpcMember: sdpc('WA'),
    agencyName: 'Washington Office of Superintendent of Public Instruction (OSPI)',
    stateLaws: [
      { name: 'SUPER Act (Student User Privacy in Education Rights)', code: 'RCW 28A.604 / SB 5419', description: 'Student user privacy in education.' },
    ],
    federalLawsNote: 'FERPA, COPPA, CIPA',
    contactEmail: null,
    contactPhone: '360-725-6162',
    website: 'https://ospi.k12.wa.us/ai',
    requiredRolesSummary: null,
    complianceSummary: 'Regular review of LEA policies; vetting of AI tools for DPA verification and encryption; use of an AI Matrix (5-step scaffolding scale).',
    dpaAvailable: null,
    aiGovernanceNotes: 'Human-Centered AI Guidance for K–12 Public Schools (2024); promotes "Human-AI-Human" (H-AI-H) approach; created statewide AI task force.',
  },
  WV: {
    code: 'WV',
    name: 'West Virginia',
    sdpcMember: sdpc('WV'),
    agencyName: 'Dept. of Education',
    stateLaws: [
      { name: 'Student Data Accessibility, Transparency, and Accountability Act', code: 'WV Code § 18-2-5h; HB 4261; HB 4316', description: 'Data Governance Manager (HB 4316).' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: 'Data Governance Manager (HB 4316).',
    complianceSummary: 'Prohibits sale of student data; parental opt-out for sharing.',
    dpaAvailable: null,
    aiGovernanceNotes: 'WVDE guidance emphasizing computational thinking.',
  },
  WI: {
    code: 'WI',
    name: 'Wisconsin',
    sdpcMember: sdpc('WI'),
    agencyName: 'Wisconsin Department of Public Instruction (DPI)',
    stateLaws: [
      { name: 'Student Data Privacy', code: 'Wis. Stat. § 111.70; § 118.225', description: 'Vetting checklist; yearly staff refresh on privacy; redaction of identifiers before AI uploads.' },
    ],
    federalLawsNote: 'FERPA, COPPA',
    contactEmail: null,
    contactPhone: '(608) 267-1071',
    website: null,
    requiredRolesSummary: null,
    complianceSummary: 'Vetting checklist for tools; yearly staff refresh on privacy; redaction of identifiers before AI uploads; restricted bargaining (2011 Budget Repair Bill).',
    dpaAvailable: null,
    aiGovernanceNotes: 'WI DPI AI Guidance V1.2; Humanistic approach (Human > AI > Human); integrates education and library settings; SEL integration focus.',
  },
  WY: {
    code: 'WY',
    name: 'Wyoming',
    sdpcMember: sdpc('WY'),
    agencyName: null,
    stateLaws: [
      { name: 'Student Data Privacy and Security', code: 'Wyo. Stat. Ann. § 21-2-202 / SF 79', description: 'Student data privacy and security.' },
    ],
    federalLawsNote: 'FERPA',
    contactEmail: null,
    contactPhone: null,
    website: null,
    requiredRolesSummary: null,
    complianceSummary: null,
    dpaAvailable: null,
    aiGovernanceNotes: 'WDE framework for policy development and student AI usage continuum.',
  },
}
