-- Comprehensive Salt Lake City bands list (deduped)
-- Insert stubs with name + slug only
INSERT INTO public.bands (name, slug)
VALUES
  ('19 Miles Per Hour', '19-miles-per-hour'),
  ('4.PLAY', '4-play'),
  ('90s Television', '90s-television'),
  ('Ablyss', 'ablyss'),
  ('Acacia Ridge', 'acacia-ridge'),
  ('Ace 52', 'ace-52'),
  ('Acid Tiger', 'acid-tiger'),
  ('Admitted Bastard', 'admitted-bastard'),
  ('Advent Horizon', 'advent-horizon'),
  ('After Eden', 'after-eden'),
  ('Air Vent Dweller', 'air-vent-dweller'),
  ('Alchemy', 'alchemy'),
  ('Alicia Stockman', 'alicia-stockman'),
  ('All Systems Fail', 'all-systems-fail'),
  ('Allred', 'allred'),
  ('Alpine Loop', 'alpine-loop'),
  ('Always Her', 'always-her'),
  ('American Humor', 'american-humor'),
  ('Apollo''s Army', 'apollo-s-army'),
  ('ATS', 'ats'),
  ('Aurhe', 'aurhe'),
  ('Awakening Autumn', 'awakening-autumn'),
  ('Awol', 'awol'),
  ('Baby Ghosts', 'baby-ghosts'),
  ('Bad Heather', 'bad-heather'),
  ('Bad Luck Brigade', 'bad-luck-brigade'),
  ('Bat Manors', 'bat-manors'),
  ('Beauty School Dropout', 'beauty-school-dropout'),
  ('Before Braille', 'before-braille'),
  ('Better in Color', 'better-in-color'),
  ('Big Trub', 'big-trub'),
  ('Black Tie Event', 'black-tie-event'),
  ('BLACKSHAPE', 'blackshape'),
  ('Bleu Grave', 'bleu-grave'),
  ('Blindlove', 'blindlove'),
  ('Bloody Cabaret', 'bloody-cabaret'),
  ('Blue Bell', 'blue-bell'),
  ('Bombs and Beating Hearts', 'bombs-and-beating-hearts'),
  ('Bone Throwers', 'bone-throwers'),
  ('Botanical Animal', 'botanical-animal'),
  ('Boxcar Kids', 'boxcar-kids'),
  ('Boycomma', 'boycomma'),
  ('Breakfast Biscuit', 'breakfast-biscuit'),
  ('Brother.', 'brother'),
  ('Bruce Lee and the Streetfighters', 'bruce-lee-and-the-streetfighters'),
  ('Buckle Busters', 'buckle-busters'),
  ('Camo', 'camo'),
  ('Cardinal Bloom', 'cardinal-bloom'),
  ('Caroline''s Spine', 'caroline-s-spine'),
  ('CarrierWave', 'carrierwave'),
  ('Casio Ghost', 'casio-ghost'),
  ('Catalogue', 'catalogue'),
  ('CAYSN', 'caysn'),
  ('Cecret Souls', 'cecret-souls'),
  ('Chac Xol', 'chac-xol'),
  ('Chainwhip', 'chainwhip'),
  ('CHALK', 'chalk'),
  ('Charlatan', 'charlatan'),
  ('Chelsea Grin', 'chelsea-grin'),
  ('Chi Chi', 'chi-chi'),
  ('Choir Boy', 'choir-boy'),
  ('Chronic Funk Disorder', 'chronic-funk-disorder'),
  ('Chunk', 'chunk'),
  ('Citizen Soldier', 'citizen-soldier'),
  ('Citrus', 'citrus'),
  ('Clear', 'clear'),
  ('Clover', 'clover'),
  ('CLUB MUNGO', 'club-mungo'),
  ('Compass Rose', 'compass-rose'),
  ('Contingency Plan', 'contingency-plan'),
  ('Coyote Hoods', 'coyote-hoods'),
  ('Crow Killer', 'crow-killer'),
  ('Cult Leader', 'cult-leader'),
  ('CUTIE', 'cutie'),
  ('Da Neighbors', 'da-neighbors'),
  ('Daytime Lover', 'daytime-lover'),
  ('Dealin'' in Dirt', 'dealin-in-dirt'),
  ('Delune', 'delune'),
  ('Desmo', 'desmo'),
  ('Devin Barrus', 'devin-barrus'),
  ('DieMonsterDie', 'diemonsterdie'),
  ('Dine Krew', 'dine-krew'),
  ('Dinosaur Bone', 'dinosaur-bone'),
  ('Dirty Birds', 'dirty-birds'),
  ('Dirty Vespuccis', 'dirty-vespuccis'),
  ('DoomCupcake', 'doomcupcake'),
  ('Down River', 'down-river'),
  ('Draize Method', 'draize-method'),
  ('Dryggs', 'dryggs'),
  ('Dustbloom', 'dustbloom'),
  ('Dvddy', 'dvddy'),
  ('Eagle Twin', 'eagle-twin'),
  ('Echo 63', 'echo-63'),
  ('Eclipse', 'eclipse'),
  ('EEWEE', 'eewee'),
  ('Eidola', 'eidola'),
  ('Eli Jackson', 'eli-jackson'),
  ('emme Packer', 'emme-packer'),
  ('Endless Struggle', 'endless-struggle'),
  ('English Budgies', 'english-budgies'),
  ('Establish', 'establish'),
  ('Ether', 'ether'),
  ('Ether Orchestra', 'ether-orchestra'),
  ('Extortionist', 'extortionist'),
  ('Eyes of Eva', 'eyes-of-eva'),
  ('EZher', 'ezher'),
  ('Fake Nice', 'fake-nice'),
  ('Fancy Ladz', 'fancy-ladz'),
  ('Fever Dreams', 'fever-dreams'),
  ('Fews & Twos', 'fews-and-twos'),
  ('Fictionist', 'fictionist'),
  ('Filth Lords', 'filth-lords'),
  ('Flamingo', 'flamingo'),
  ('Folk Hogan', 'folk-hogan'),
  ('Forget Tomorrow', 'forget-tomorrow'),
  ('Form of Rocket', 'form-of-rocket'),
  ('Fox Van Cleef', 'fox-van-cleef'),
  ('FOXTIDE', 'foxtide'),
  ('future.exboyfriend', 'future-exboyfriend'),
  ('Gaza', 'gaza'),
  ('Glinting Gems', 'glinting-gems'),
  ('Go Metric', 'go-metric'),
  ('Good as Gone', 'good-as-gone'),
  ('Graveljaw Keaton', 'graveljaw-keaton'),
  ('GRGL', 'grgl'),
  ('Guava Tree', 'guava-tree'),
  ('Handicapitalist', 'handicapitalist'),
  ('Harbor Patrol', 'harbor-patrol'),
  ('Hawker Roam', 'hawker-roam'),
  ('Health Care', 'health-care'),
  ('Heathen Ass Worship', 'heathen-ass-worship'),
  ('Hemlock', 'hemlock'),
  ('Her Candane', 'her-candane'),
  ('Hi-Fi Murder', 'hi-fi-murder'),
  ('Hollow Hill', 'hollow-hill'),
  ('Holy Water Buffalo', 'holy-water-buffalo'),
  ('Homestyle Dinner Rolls', 'homestyle-dinner-rolls'),
  ('Howl', 'howl'),
  ('Hudson River School', 'hudson-river-school'),
  ('Huldra', 'huldra'),
  ('Hurtado', 'hurtado'),
  ('HXSTAGE', 'hxstage'),
  ('I AM', 'i-am'),
  ('I Am Electric', 'i-am-electric'),
  ('I Dont Know How But They Found Me (IDKHOW)', 'i-dont-know-how-but-they-found-me'),
  ('Iceburn', 'iceburn'),
  ('Ideal Horizon', 'ideal-horizon'),
  ('Illegal Beagle', 'illegal-beagle'),
  ('Illicit Thoughts', 'illicit-thoughts'),
  ('IMAGE/INTENT', 'image-intent'),
  ('Imagine Dragons', 'imagine-dragons'),
  ('In the Wave', 'in-the-wave'),
  ('In\\error', 'in-error'),
  ('Incamera', 'incamera'),
  ('Insight', 'insight'),
  ('Jackass', 'jackass'),
  ('Jay Warren', 'jay-warren'),
  ('Jesus or Genome', 'jesus-or-genome'),
  ('Joshua James', 'joshua-james'),
  ('Juse', 'juse'),
  ('Katagory V', 'katagory-v'),
  ('Keep Close', 'keep-close'),
  ('Kill Minus Nine', 'kill-minus-nine'),
  ('Killbot', 'killbot'),
  ('King Niko', 'king-niko'),
  ('Krooked Kings', 'krooked-kings'),
  ('La Verkin', 'la-verkin'),
  ('Lantern By Sea', 'lantern-by-sea'),
  ('Lapsed & Nonnon', 'lapsed-and-nonnon'),
  ('Larusso', 'larusso'),
  ('Late Night Savior', 'late-night-savior'),
  ('Laughter', 'laughter'),
  ('Liar''s Tongue', 'liar-s-tongue'),
  ('Life Over Law', 'life-over-law'),
  ('Lighten Up, Francis', 'lighten-up-francis'),
  ('Little Moon', 'little-moon'),
  ('Living in Fiction', 'living-in-fiction'),
  ('Loafa', 'loafa'),
  ('Local Natives', 'local-natives'),
  ('Lonely Heights', 'lonely-heights'),
  ('Loom', 'loom'),
  ('Lord Mandrake', 'lord-mandrake'),
  ('Lord Vox', 'lord-vox'),
  ('Low Profile', 'low-profile'),
  ('Mammoth', 'mammoth'),
  ('Manlyman', 'manlyman'),
  ('Mary Mother of Bear', 'mary-mother-of-bear'),
  ('Media Queen', 'media-queen'),
  ('Meg & Dia', 'meg-and-dia'),
  ('MELO', 'melo'),
  ('Midnite Rollercoaster', 'midnite-rollercoaster'),
  ('Mindy Gledhill', 'mindy-gledhill'),
  ('Miss Valentine', 'miss-valentine'),
  ('Misty', 'misty'),
  ('Mock Tour', 'mock-tour'),
  ('Monochrome', 'monochrome'),
  ('Mopsy', 'mopsy'),
  ('Mortigi Tempo', 'mortigi-tempo'),
  ('Mowth', 'mowth'),
  ('Mr Trout', 'mr-trout'),
  ('Muscle Hawk', 'muscle-hawk'),
  ('Mystöry of X', 'mystory-of-x'),
  ('NADEZHDA', 'nadezhda'),
  ('Negative Charge', 'negative-charge'),
  ('Neon Trees', 'neon-trees'),
  ('Nightbreakers', 'nightbreakers'),
  ('No Delay', 'no-delay'),
  ('No Jure', 'no-jure'),
  ('No Release', 'no-release'),
  ('No Such Animal', 'no-such-animal'),
  ('Noble Bodies', 'noble-bodies'),
  ('NVM', 'nvm'),
  ('Old Man Johnson', 'old-man-johnson'),
  ('Open Door Policy', 'open-door-policy'),
  ('OrcaMind', 'orcamind'),
  ('Orpheum', 'orpheum'),
  ('Over Under', 'over-under'),
  ('Oxcross', 'oxcross'),
  ('Oxford Grey', 'oxford-grey'),
  ('Parade the Bug', 'parade-the-bug'),
  ('Penrose', 'penrose'),
  ('Perfectly Flawed', 'perfectly-flawed'),
  ('Peter Breinholt', 'peter-breinholt'),
  ('Pinguin Mofex', 'pinguin-mofex'),
  ('Pirates of the Promised Land', 'pirates-of-the-promised-land'),
  ('Pixie and the Party Grass Boys', 'pixie-and-the-party-grass-boys'),
  ('Plastic Cherries', 'plastic-cherries'),
  ('Poet Bones', 'poet-bones'),
  ('Poolhouse', 'poolhouse'),
  ('Preacher & the Parasites', 'preacher-and-the-parasites'),
  ('Problem Daughter', 'problem-daughter'),
  ('Puddle Mountain Ramblers', 'puddle-mountain-ramblers'),
  ('Queenadilla', 'queenadilla'),
  ('Quinn Allman', 'quinn-allman'),
  ('Racist Kramer', 'racist-kramer'),
  ('Raspberry Protocol', 'raspberry-protocol'),
  ('Rated Hero', 'rated-hero'),
  ('Recently Decent', 'recently-decent'),
  ('Red Pete', 'red-pete'),
  ('Rejected Takeoff', 'rejected-takeoff'),
  ('RIFF TKR', 'riff-tkr'),
  ('Rile', 'rile'),
  ('Ritt Momney', 'ritt-momney'),
  ('Rodeo Boys', 'rodeo-boys'),
  ('Roseburg', 'roseburg'),
  ('Royal Bliss', 'royal-bliss'),
  ('Runaway Fighter', 'runaway-fighter'),
  ('Runaway Fire', 'runaway-fire'),
  ('Ryan Shupe and the RubberBand', 'ryan-shupe-and-the-rubberband'),
  ('S.L.F.M', 's-l-f-m'),
  ('Saemore', 'saemore'),
  ('Sage Lane', 'sage-lane'),
  ('Salduro', 'salduro'),
  ('Salt City Bandits', 'salt-city-bandits'),
  ('Salt Lake Alternative Jazz Orchestra (SLAJO)', 'salt-lake-alternative-jazz-orchestra'),
  ('Salt Lake Spitfires', 'salt-lake-spitfires'),
  ('Salt town Greasers', 'salt-town-greasers'),
  ('Sammy Brue', 'sammy-brue'),
  ('Saving Sydney', 'saving-sydney'),
  ('Say It Back', 'say-it-back'),
  ('Scarlet City', 'scarlet-city'),
  ('Scarlet Rain', 'scarlet-rain'),
  ('Sea Elephant', 'sea-elephant'),
  ('Second Guess', 'second-guess'),
  ('Second Rate Superhero', 'second-rate-superhero'),
  ('Seventh Seal', 'seventh-seal'),
  ('Shadow of Preachers', 'shadow-of-preachers'),
  ('Shaky Slaps', 'shaky-slaps'),
  ('Shecock', 'shecock'),
  ('Sherlock', 'sherlock'),
  ('Shrink the Giant', 'shrink-the-giant'),
  ('Silver Cup', 'silver-cup'),
  ('Sleep Cult', 'sleep-cult'),
  ('Slick Daddies', 'slick-daddies'),
  ('Smarter Than Katie', 'smarter-than-katie'),
  ('SoulFang', 'soulfang'),
  ('Soultree', 'soultree'),
  ('Special Edward', 'special-edward'),
  ('Spitting Teeth', 'spitting-teeth'),
  ('Starmy', 'starmy'),
  ('Static Waves', 'static-waves'),
  ('Steal Fate', 'steal-fate'),
  ('Stereo Ranger', 'stereo-ranger'),
  ('Stiletto', 'stiletto'),
  ('Strawberry Cough', 'strawberry-cough'),
  ('Subject To Change', 'subject-to-change'),
  ('SubRosa', 'subrosa'),
  ('Sun House Healers', 'sun-house-healers'),
  ('Sunfish', 'sunfish'),
  ('Sunsleeper', 'sunsleeper'),
  ('Swarmer', 'swarmer'),
  ('Swell Merchants', 'swell-merchants'),
  ('Swerved By Blondes', 'swerved-by-blondes'),
  ('Swim Herschel Swim', 'swim-herschel-swim'),
  ('Sympathy Pain', 'sympathy-pain'),
  ('Take the Fall', 'take-the-fall'),
  ('Takeover', 'takeover'),
  ('Talia Keys', 'talia-keys'),
  ('Teddy Picker', 'teddy-picker'),
  ('The Aces', 'the-aces'),
  ('The Alpines', 'the-alpines'),
  ('The Artificial Flower Company', 'the-artificial-flower-company'),
  ('The Atheists', 'the-atheists'),
  ('The Backseat Lovers', 'the-backseat-lovers'),
  ('The Boomsticks', 'the-boomsticks'),
  ('The Brobecks', 'the-brobecks'),
  ('The Corleones', 'the-corleones'),
  ('the Founding', 'the-founding'),
  ('The Gontiks', 'the-gontiks'),
  ('The Hollering Pines', 'the-hollering-pines'),
  ('The Hung Ups', 'the-hung-ups'),
  ('The Lionelle', 'the-lionelle'),
  ('The Lovestrange', 'the-lovestrange'),
  ('The Madeline', 'the-madeline'),
  ('The Modifiers', 'the-modifiers'),
  ('The Mooks', 'the-mooks'),
  ('The Moss', 'the-moss'),
  ('The Moth & The Flame', 'the-moth-and-the-flame'),
  ('The Moths', 'the-moths'),
  ('The Naked Eyes', 'the-naked-eyes'),
  ('The National Parks', 'the-national-parks'),
  ('The New Electric Sound', 'the-new-electric-sound'),
  ('The New Transit Direction', 'the-new-transit-direction'),
  ('The Nods', 'the-nods'),
  ('The Obvious', 'the-obvious'),
  ('The Osmonds', 'the-osmonds'),
  ('The Painted Roses', 'the-painted-roses'),
  ('The Persistent Divide', 'the-persistent-divide'),
  ('The Red Bennies', 'the-red-bennies'),
  ('The Secret Light', 'the-secret-light'),
  ('The Shindas', 'the-shindas'),
  ('The Skaficionados', 'the-skaficionados'),
  ('The Sons-In-Law of the Daughters of the Utah Pioneers', 'the-sons-in-law-of-the-daughters-of-the-utah-pioneers'),
  ('The Stench', 'the-stench'),
  ('The Upstarts', 'the-upstarts'),
  ('The Used', 'the-used'),
  ('The What-Nots', 'the-what-nots'),
  ('The Zissous', 'the-zissous'),
  ('Three%Hero', 'three-hero'),
  ('Thunderfist', 'thunderfist'),
  ('Tijuana Bible', 'tijuana-bible'),
  ('Tolchock Trio', 'tolchock-trio'),
  ('Tragic Black', 'tragic-black'),
  ('Trey Warner', 'trey-warner'),
  ('Tyler Gould', 'tyler-gould'),
  ('UltraVatic', 'ultravatic'),
  ('Unlucky Boys', 'unlucky-boys'),
  ('UTK', 'utk'),
  ('Uzi and Ari', 'uzi-and-ari'),
  ('V-Vast', 'v-vast'),
  ('VadaWave', 'vadawave'),
  ('Vaseline the band', 'vaseline-the-band'),
  ('Victims Willing', 'victims-willing'),
  ('Vile Blue Shades', 'vile-blue-shades'),
  ('Vintage Overdrive', 'vintage-overdrive'),
  ('Voidsmen', 'voidsmen'),
  ('Waist Deep', 'waist-deep'),
  ('Westward the Tide', 'westward-the-tide'),
  ('Whisperhawk', 'whisperhawk'),
  ('White Noise Vision', 'white-noise-vision'),
  ('Wicked Bears', 'wicked-bears'),
  ('Will Saratin', 'will-saratin'),
  ('Willöh', 'willoh'),
  ('Wisebird', 'wisebird'),
  ('With Andrea', 'with-andrea'),
  ('Worlds Worst', 'worlds-worst'),
  ('Zigga', 'zigga')
ON CONFLICT (slug) DO NOTHING;
