/* eslint-disable jsx-a11y/alt-text */
'use client';

import {
    Document,
    Page,
    Text,
    View,
    StyleSheet,
    Font,
    Image,
} from '@react-pdf/renderer';

// Register fonts
Font.register({
    family: 'Inter',
    fonts: [
        { src: 'https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hjp-Ek-_EeA.woff' },
        { src: 'https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fAZ9hjp-Ek-_EeA.woff', fontWeight: 700 },
    ],
});

const styles = StyleSheet.create({
    page: {
        padding: 40,
        fontFamily: 'Inter',
        backgroundColor: '#FFFFFF',
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 2,
        borderBottomColor: '#1F2937',
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 700,
        color: '#111827',
        marginBottom: 4,
    },
    subtitle: {
        fontSize: 12,
        color: '#6B7280',
    },
    section: {
        marginBottom: 20,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: 700,
        color: '#374151',
        marginBottom: 8,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    row: {
        flexDirection: 'row',
        marginBottom: 4,
    },
    bullet: {
        width: 10,
        fontSize: 10,
        color: '#4B5563',
    },
    content: {
        fontSize: 10,
        color: '#4B5563',
        flex: 1,
        lineHeight: 1.4,
    },
    grid: {
        flexDirection: 'row',
        gap: 20,
        marginTop: 20,
    },
    column: {
        flex: 1,
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        paddingTop: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    footerText: {
        fontSize: 8,
        color: '#9CA3AF',
    },
    box: {
        padding: 10,
        backgroundColor: '#F3F4F6',
        borderRadius: 4,
        marginTop: 10,
    },
    boxTitle: {
        fontSize: 10,
        fontWeight: 700,
        color: '#111827',
        marginBottom: 4,
    },
    boxText: {
        fontSize: 10,
        color: '#4B5563',
        fontStyle: 'italic',
    }
});

interface BoardOnePagerProps {
    data: {
        district: string;
        generatedAt: string;
        sections: {
            title: string;
            content: string[];
        }[];
        riskStatement: string;
        complianceStatement: string;
    };
}

export const BoardOnePagerPDF = ({ data }: BoardOnePagerProps) => (
    <Document>
        <Page size="A4" style={styles.page}>
            {/* Header */}
            <View style={styles.header}>
                <Text style={styles.title}>AI Governance Strategy</Text>
                <Text style={styles.subtitle}>{data.district} • Executive Summary</Text>
            </View>

            {/* Main Content Sections */}
            {data.sections.map((section, idx) => (
                <View key={idx} style={styles.section}>
                    <Text style={styles.sectionTitle}>{section.title}</Text>
                    {section.content.map((item, i) => (
                        <View key={i} style={styles.row}>
                            <Text style={styles.bullet}>•</Text>
                            <Text style={styles.content}>{item}</Text>
                        </View>
                    ))}
                </View>
            ))}

            {/* Footer Boxes */}
            <View style={styles.grid}>
                <View style={styles.column}>
                    <View style={{ ...styles.box, backgroundColor: '#FEF2F2' }}>
                        <Text style={{ ...styles.boxTitle, color: '#991B1B' }}>Risk Statement</Text>
                        <Text style={styles.boxText}>{data.riskStatement}</Text>
                    </View>
                </View>
                <View style={styles.column}>
                    <View style={{ ...styles.box, backgroundColor: '#F0F9FF' }}>
                        <Text style={{ ...styles.boxTitle, color: '#075985' }}>Compliance</Text>
                        <Text style={styles.boxText}>{data.complianceStatement}</Text>
                    </View>
                </View>
            </View>

            {/* Footer */}
            <View style={styles.footer}>
                <Text style={styles.footerText}>Generated by District AI Readiness OS (DAROS)</Text>
                <Text style={styles.footerText}>{new Date(data.generatedAt).toLocaleDateString()}</Text>
            </View>
        </Page>
    </Document>
);
